create database customer_behavior;

use customer_behavior;

SELECT * From customer limit 20;

-- Answer to business questions:
-- 1. What is the total revenue generated by male vs female customers?
Select gender, sum(purchase_amount_usd) as revenue
from customer
group by gender;

-- 2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount_usd
From customer
where discount_applied = 'Yes' and purchase_amount_usd >= (Select avg(purchase_amount_usd) from customer)
Order by purchase_amount_usd DESC;

-- 3. Which are the top 5 products with the highest average review rating?
Select item_purchased, round(avg(review_rating),2) as average_product_rating
from customer
group by item_purchased
Order by average_product_rating DESC
LIMIT 5;

-- 4. Compare the average purchase amounts between standard and express shipping.
Select shipping_type, avg(purchase_amount_usd) as avg_purchase_amounts
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount_usd),2) as average_spend,
round(sum(purchase_amount_usd),2) as total_revenue
From customer
group by subscription_status
order by total_revenue, average_spend DESC;

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased, round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*), 2) as discount_rate
From customer
group by item_purchased
Order by discount_rate DESC
LIMIT 5;

-- 7. Segment customers into New, Returning, Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
Select customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 then 'New'
    WHEN previous_purchases Between 2 AND 10 then 'Returning'
    ELSE 'Loyal'
    END as customer_segment
from customer
)

Select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment;

-- 8. What are the top 3 most purchased products within each category
with item_counts as (
Select category, item_purchased, count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

Select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
From customer
where previous_purchases > 5
group by subscription_status;

-- 10. what is the revenue contribution of each age group
Select age_group, sum(purchase_amount_usd) as total_revenue
from customer
group by age_group
order by total_revenue DESC;